// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Data.Gym.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "PogoprotosData.pbobjc.h"
 #import "PogoprotosDataPlayer.pbobjc.h"
 #import "PogoprotosMapFort.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FortData;
@class GymMembership;
@class PlayerPublicProfile;
@class PokemonData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PogoprotosDataGymRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PogoprotosDataGymRoot : GPBRootObject
@end

#pragma mark - GymMembership

typedef GPB_ENUM(GymMembership_FieldNumber) {
  GymMembership_FieldNumber_PokemonData = 1,
  GymMembership_FieldNumber_TrainerPublicProfile = 2,
  GymMembership_FieldNumber_TrainingPokemon = 3,
};

@interface GymMembership : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *pokemonData;
/** Test to see if @c pokemonData has been set. */
@property(nonatomic, readwrite) BOOL hasPokemonData;

@property(nonatomic, readwrite, strong, null_resettable) PlayerPublicProfile *trainerPublicProfile;
/** Test to see if @c trainerPublicProfile has been set. */
@property(nonatomic, readwrite) BOOL hasTrainerPublicProfile;

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *trainingPokemon;
/** Test to see if @c trainingPokemon has been set. */
@property(nonatomic, readwrite) BOOL hasTrainingPokemon;

@end

#pragma mark - GymState

typedef GPB_ENUM(GymState_FieldNumber) {
  GymState_FieldNumber_FortData = 1,
  GymState_FieldNumber_MembershipsArray = 2,
  GymState_FieldNumber_DeployLockout = 3,
};

@interface GymState : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) FortData *fortData;
/** Test to see if @c fortData has been set. */
@property(nonatomic, readwrite) BOOL hasFortData;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GymMembership*> *membershipsArray;
/** The number of items in @c membershipsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger membershipsArray_Count;

@property(nonatomic, readwrite) BOOL deployLockout;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
