// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Data.Avatar.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AvatarCustomization_Label

typedef GPB_ENUM(AvatarCustomization_Label) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AvatarCustomization_Label_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AvatarCustomization_Label_UnsetLabel = 0,
  AvatarCustomization_Label_Default = 1,
  AvatarCustomization_Label_Owned = 2,
  AvatarCustomization_Label_Featured = 3,
  AvatarCustomization_Label_New = 4,
  AvatarCustomization_Label_Sale = 5,
  AvatarCustomization_Label_Purchasable = 6,
  AvatarCustomization_Label_Unlockable = 7,
  AvatarCustomization_Label_Viewed = 8,
};

GPBEnumDescriptor *AvatarCustomization_Label_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AvatarCustomization_Label_IsValidValue(int32_t value);

#pragma mark - PogoprotosDataAvatarRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PogoprotosDataAvatarRoot : GPBRootObject
@end

#pragma mark - AvatarCustomization

typedef GPB_ENUM(AvatarCustomization_FieldNumber) {
  AvatarCustomization_FieldNumber_AvatarTemplateId = 1,
  AvatarCustomization_FieldNumber_LabelsArray = 2,
};

@interface AvatarCustomization : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarTemplateId;

// |labelsArray| contains |AvatarCustomization_Label|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *labelsArray;
/** The number of items in @c labelsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger labelsArray_Count;

@end

#pragma mark - AvatarItem

typedef GPB_ENUM(AvatarItem_FieldNumber) {
  AvatarItem_FieldNumber_AvatarTemplateId = 1,
  AvatarItem_FieldNumber_NewTimestampMs = 2,
  AvatarItem_FieldNumber_Viewed = 3,
};

@interface AvatarItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarTemplateId;

@property(nonatomic, readwrite) int64_t newTimestampMs;

@property(nonatomic, readwrite) BOOL viewed;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
