// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Map.Pokemon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "PogoprotosEnums.pbobjc.h"
 #import "PogoprotosData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FoodValue;
@class PokemonData;
@class PokemonDisplay;
GPB_ENUM_FWD_DECLARE(PokemonId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PogoprotosMapPokemonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PogoprotosMapPokemonRoot : GPBRootObject
@end

#pragma mark - LobbyPokemon

typedef GPB_ENUM(LobbyPokemon_FieldNumber) {
  LobbyPokemon_FieldNumber_Id_p = 1,
  LobbyPokemon_FieldNumber_PokedexId = 2,
  LobbyPokemon_FieldNumber_Cp = 3,
  LobbyPokemon_FieldNumber_PercentHealth = 4,
};

@interface LobbyPokemon : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) enum PokemonId pokedexId;

@property(nonatomic, readwrite) int32_t cp;

@property(nonatomic, readwrite) float percentHealth;

@end

/**
 * Fetches the raw value of a @c LobbyPokemon's @c pokedexId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t LobbyPokemon_PokedexId_RawValue(LobbyPokemon *message);
/**
 * Sets the raw value of an @c LobbyPokemon's @c pokedexId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetLobbyPokemon_PokedexId_RawValue(LobbyPokemon *message, int32_t value);

#pragma mark - MapPokemon

typedef GPB_ENUM(MapPokemon_FieldNumber) {
  MapPokemon_FieldNumber_SpawnPointId = 1,
  MapPokemon_FieldNumber_EncounterId = 2,
  MapPokemon_FieldNumber_PokemonId = 3,
  MapPokemon_FieldNumber_ExpirationTimestampMs = 4,
  MapPokemon_FieldNumber_Latitude = 5,
  MapPokemon_FieldNumber_Longitude = 6,
  MapPokemon_FieldNumber_PokemonDisplay = 7,
};

@interface MapPokemon : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite) enum PokemonId pokemonId;

/** After this timestamp, the pokemon will be gone. */
@property(nonatomic, readwrite) int64_t expirationTimestampMs;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite, strong, null_resettable) PokemonDisplay *pokemonDisplay;
/** Test to see if @c pokemonDisplay has been set. */
@property(nonatomic, readwrite) BOOL hasPokemonDisplay;

@end

/**
 * Fetches the raw value of a @c MapPokemon's @c pokemonId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MapPokemon_PokemonId_RawValue(MapPokemon *message);
/**
 * Sets the raw value of an @c MapPokemon's @c pokemonId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMapPokemon_PokemonId_RawValue(MapPokemon *message, int32_t value);

#pragma mark - MotivatedPokemon

typedef GPB_ENUM(MotivatedPokemon_FieldNumber) {
  MotivatedPokemon_FieldNumber_Pokemon = 1,
  MotivatedPokemon_FieldNumber_DeployMs = 2,
  MotivatedPokemon_FieldNumber_CpWhenDeployed = 3,
  MotivatedPokemon_FieldNumber_MotivationNow = 4,
  MotivatedPokemon_FieldNumber_CpNow = 5,
  MotivatedPokemon_FieldNumber_BerryValue = 6,
  MotivatedPokemon_FieldNumber_FeedCooldownDurationMillis = 7,
  MotivatedPokemon_FieldNumber_FoodValueArray = 8,
};

@interface MotivatedPokemon : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *pokemon;
/** Test to see if @c pokemon has been set. */
@property(nonatomic, readwrite) BOOL hasPokemon;

@property(nonatomic, readwrite) int64_t deployMs;

@property(nonatomic, readwrite) int32_t cpWhenDeployed;

@property(nonatomic, readwrite) double motivationNow;

@property(nonatomic, readwrite) int32_t cpNow;

@property(nonatomic, readwrite) float berryValue;

@property(nonatomic, readwrite) int64_t feedCooldownDurationMillis;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FoodValue*> *foodValueArray;
/** The number of items in @c foodValueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger foodValueArray_Count;

@end

#pragma mark - NearbyPokemon

typedef GPB_ENUM(NearbyPokemon_FieldNumber) {
  NearbyPokemon_FieldNumber_PokemonId = 1,
  NearbyPokemon_FieldNumber_DistanceInMeters = 2,
  NearbyPokemon_FieldNumber_EncounterId = 3,
  NearbyPokemon_FieldNumber_FortId = 4,
  NearbyPokemon_FieldNumber_FortImageURL = 5,
  NearbyPokemon_FieldNumber_PokemonDisplay = 6,
};

@interface NearbyPokemon : GPBMessage

@property(nonatomic, readwrite) enum PokemonId pokemonId;

@property(nonatomic, readwrite) float distanceInMeters;

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortImageURL;

@property(nonatomic, readwrite, strong, null_resettable) PokemonDisplay *pokemonDisplay;
/** Test to see if @c pokemonDisplay has been set. */
@property(nonatomic, readwrite) BOOL hasPokemonDisplay;

@end

/**
 * Fetches the raw value of a @c NearbyPokemon's @c pokemonId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NearbyPokemon_PokemonId_RawValue(NearbyPokemon *message);
/**
 * Sets the raw value of an @c NearbyPokemon's @c pokemonId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNearbyPokemon_PokemonId_RawValue(NearbyPokemon *message, int32_t value);

#pragma mark - WildPokemon

typedef GPB_ENUM(WildPokemon_FieldNumber) {
  WildPokemon_FieldNumber_EncounterId = 1,
  WildPokemon_FieldNumber_LastModifiedTimestampMs = 2,
  WildPokemon_FieldNumber_Latitude = 3,
  WildPokemon_FieldNumber_Longitude = 4,
  WildPokemon_FieldNumber_SpawnPointId = 5,
  WildPokemon_FieldNumber_PokemonData = 7,
  WildPokemon_FieldNumber_TimeTillHiddenMs = 11,
};

@interface WildPokemon : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite) int64_t lastModifiedTimestampMs;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite, strong, null_resettable) PokemonData *pokemonData;
/** Test to see if @c pokemonData has been set. */
@property(nonatomic, readwrite) BOOL hasPokemonData;

@property(nonatomic, readwrite) int32_t timeTillHiddenMs;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
