// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Networking.Requests.Messages.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "PogoprotosInventoryItem.pbobjc.h"
 #import "PogoprotosDataBattle.pbobjc.h"
 #import "PogoprotosEnums.pbobjc.h"
 #import "PogoprotosDataPlayer.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BattleAction;
@class ContactSettings;
@class GetPlayerMessage_PlayerLocale;
@class PlayerAvatar;
GPB_ENUM_FWD_DECLARE(BadgeType);
GPB_ENUM_FWD_DECLARE(ItemId);
GPB_ENUM_FWD_DECLARE(NotificationState);
GPB_ENUM_FWD_DECLARE(Platform);
GPB_ENUM_FWD_DECLARE(PlayerAvatarType);
GPB_ENUM_FWD_DECLARE(PokemonId);
GPB_ENUM_FWD_DECLARE(TeamColor);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PogoprotosNetworkingRequestsMessagesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PogoprotosNetworkingRequestsMessagesRoot : GPBRootObject
@end

#pragma mark - AddFortModifierMessage

typedef GPB_ENUM(AddFortModifierMessage_FieldNumber) {
  AddFortModifierMessage_FieldNumber_ModifierType = 1,
  AddFortModifierMessage_FieldNumber_FortId = 2,
  AddFortModifierMessage_FieldNumber_PlayerLatitude = 3,
  AddFortModifierMessage_FieldNumber_PlayerLongitude = 4,
};

@interface AddFortModifierMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId modifierType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

/**
 * Fetches the raw value of a @c AddFortModifierMessage's @c modifierType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AddFortModifierMessage_ModifierType_RawValue(AddFortModifierMessage *message);
/**
 * Sets the raw value of an @c AddFortModifierMessage's @c modifierType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAddFortModifierMessage_ModifierType_RawValue(AddFortModifierMessage *message, int32_t value);

#pragma mark - AttackGymMessage

typedef GPB_ENUM(AttackGymMessage_FieldNumber) {
  AttackGymMessage_FieldNumber_GymId = 1,
  AttackGymMessage_FieldNumber_BattleId = 2,
  AttackGymMessage_FieldNumber_AttackActionsArray = 3,
  AttackGymMessage_FieldNumber_LastRetrievedAction = 4,
  AttackGymMessage_FieldNumber_PlayerLatitude = 5,
  AttackGymMessage_FieldNumber_PlayerLongitude = 6,
};

@interface AttackGymMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *gymId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *battleId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BattleAction*> *attackActionsArray;
/** The number of items in @c attackActionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attackActionsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) BattleAction *lastRetrievedAction;
/** Test to see if @c lastRetrievedAction has been set. */
@property(nonatomic, readwrite) BOOL hasLastRetrievedAction;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - CatchPokemonMessage

typedef GPB_ENUM(CatchPokemonMessage_FieldNumber) {
  CatchPokemonMessage_FieldNumber_EncounterId = 1,
  CatchPokemonMessage_FieldNumber_Pokeball = 2,
  CatchPokemonMessage_FieldNumber_NormalizedReticleSize = 3,
  CatchPokemonMessage_FieldNumber_SpawnPointId = 4,
  CatchPokemonMessage_FieldNumber_HitPokemon = 5,
  CatchPokemonMessage_FieldNumber_SpinModifier = 6,
  CatchPokemonMessage_FieldNumber_NormalizedHitPosition = 7,
};

@interface CatchPokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite) enum ItemId pokeball;

@property(nonatomic, readwrite) double normalizedReticleSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite) BOOL hitPokemon;

@property(nonatomic, readwrite) double spinModifier;

@property(nonatomic, readwrite) double normalizedHitPosition;

@end

/**
 * Fetches the raw value of a @c CatchPokemonMessage's @c pokeball property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t CatchPokemonMessage_Pokeball_RawValue(CatchPokemonMessage *message);
/**
 * Sets the raw value of an @c CatchPokemonMessage's @c pokeball property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetCatchPokemonMessage_Pokeball_RawValue(CatchPokemonMessage *message, int32_t value);

#pragma mark - CheckAwardedBadgesMessage

/**
 * No message needed.
 **/
@interface CheckAwardedBadgesMessage : GPBMessage

@end

#pragma mark - CheckChallengeMessage

typedef GPB_ENUM(CheckChallengeMessage_FieldNumber) {
  CheckChallengeMessage_FieldNumber_DebugRequest = 1,
};

@interface CheckChallengeMessage : GPBMessage

@property(nonatomic, readwrite) BOOL debugRequest;

@end

#pragma mark - ClaimCodenameMessage

typedef GPB_ENUM(ClaimCodenameMessage_FieldNumber) {
  ClaimCodenameMessage_FieldNumber_Codename = 1,
  ClaimCodenameMessage_FieldNumber_Force = 2,
};

@interface ClaimCodenameMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *codename;

@property(nonatomic, readwrite) BOOL force;

@end

#pragma mark - CollectDailyBonusMessage

/**
 * No message needed.
 **/
@interface CollectDailyBonusMessage : GPBMessage

@end

#pragma mark - CollectDailyDefenderBonusMessage

/**
 * No message needed.
 **/
@interface CollectDailyDefenderBonusMessage : GPBMessage

@end

#pragma mark - DiskEncounterMessage

typedef GPB_ENUM(DiskEncounterMessage_FieldNumber) {
  DiskEncounterMessage_FieldNumber_EncounterId = 1,
  DiskEncounterMessage_FieldNumber_FortId = 2,
  DiskEncounterMessage_FieldNumber_PlayerLatitude = 3,
  DiskEncounterMessage_FieldNumber_PlayerLongitude = 4,
};

@interface DiskEncounterMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - DownloadItemTemplatesMessage

typedef GPB_ENUM(DownloadItemTemplatesMessage_FieldNumber) {
  DownloadItemTemplatesMessage_FieldNumber_Paginate = 1,
  DownloadItemTemplatesMessage_FieldNumber_PageOffset = 2,
  DownloadItemTemplatesMessage_FieldNumber_PageTimestamp = 3,
};

@interface DownloadItemTemplatesMessage : GPBMessage

@property(nonatomic, readwrite) BOOL paginate;

@property(nonatomic, readwrite) int32_t pageOffset;

@property(nonatomic, readwrite) uint64_t pageTimestamp;

@end

#pragma mark - DownloadRemoteConfigVersionMessage

typedef GPB_ENUM(DownloadRemoteConfigVersionMessage_FieldNumber) {
  DownloadRemoteConfigVersionMessage_FieldNumber_Platform = 1,
  DownloadRemoteConfigVersionMessage_FieldNumber_DeviceManufacturer = 2,
  DownloadRemoteConfigVersionMessage_FieldNumber_DeviceModel = 3,
  DownloadRemoteConfigVersionMessage_FieldNumber_Locale = 4,
  DownloadRemoteConfigVersionMessage_FieldNumber_AppVersion = 5,
};

@interface DownloadRemoteConfigVersionMessage : GPBMessage

@property(nonatomic, readwrite) enum Platform platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceManufacturer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

@property(nonatomic, readwrite) uint32_t appVersion;

@end

/**
 * Fetches the raw value of a @c DownloadRemoteConfigVersionMessage's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t DownloadRemoteConfigVersionMessage_Platform_RawValue(DownloadRemoteConfigVersionMessage *message);
/**
 * Sets the raw value of an @c DownloadRemoteConfigVersionMessage's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetDownloadRemoteConfigVersionMessage_Platform_RawValue(DownloadRemoteConfigVersionMessage *message, int32_t value);

#pragma mark - DownloadSettingsMessage

typedef GPB_ENUM(DownloadSettingsMessage_FieldNumber) {
  DownloadSettingsMessage_FieldNumber_Hash_p = 1,
};

@interface DownloadSettingsMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@end

#pragma mark - EchoMessage

/**
 * No message needed.
 **/
@interface EchoMessage : GPBMessage

@end

#pragma mark - EncounterMessage

typedef GPB_ENUM(EncounterMessage_FieldNumber) {
  EncounterMessage_FieldNumber_EncounterId = 1,
  EncounterMessage_FieldNumber_SpawnPointId = 2,
  EncounterMessage_FieldNumber_PlayerLatitude = 3,
  EncounterMessage_FieldNumber_PlayerLongitude = 4,
};

@interface EncounterMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - EncounterTutorialCompleteMessage

typedef GPB_ENUM(EncounterTutorialCompleteMessage_FieldNumber) {
  EncounterTutorialCompleteMessage_FieldNumber_PokemonId = 1,
};

@interface EncounterTutorialCompleteMessage : GPBMessage

@property(nonatomic, readwrite) enum PokemonId pokemonId;

@end

/**
 * Fetches the raw value of a @c EncounterTutorialCompleteMessage's @c pokemonId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t EncounterTutorialCompleteMessage_PokemonId_RawValue(EncounterTutorialCompleteMessage *message);
/**
 * Sets the raw value of an @c EncounterTutorialCompleteMessage's @c pokemonId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetEncounterTutorialCompleteMessage_PokemonId_RawValue(EncounterTutorialCompleteMessage *message, int32_t value);

#pragma mark - EquipBadgeMessage

typedef GPB_ENUM(EquipBadgeMessage_FieldNumber) {
  EquipBadgeMessage_FieldNumber_BadgeType = 1,
};

@interface EquipBadgeMessage : GPBMessage

@property(nonatomic, readwrite) enum BadgeType badgeType;

@end

/**
 * Fetches the raw value of a @c EquipBadgeMessage's @c badgeType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t EquipBadgeMessage_BadgeType_RawValue(EquipBadgeMessage *message);
/**
 * Sets the raw value of an @c EquipBadgeMessage's @c badgeType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetEquipBadgeMessage_BadgeType_RawValue(EquipBadgeMessage *message, int32_t value);

#pragma mark - EvolvePokemonMessage

typedef GPB_ENUM(EvolvePokemonMessage_FieldNumber) {
  EvolvePokemonMessage_FieldNumber_PokemonId = 1,
  EvolvePokemonMessage_FieldNumber_EvolutionItemRequirement = 2,
};

@interface EvolvePokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite) enum ItemId evolutionItemRequirement;

@end

/**
 * Fetches the raw value of a @c EvolvePokemonMessage's @c evolutionItemRequirement property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t EvolvePokemonMessage_EvolutionItemRequirement_RawValue(EvolvePokemonMessage *message);
/**
 * Sets the raw value of an @c EvolvePokemonMessage's @c evolutionItemRequirement property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetEvolvePokemonMessage_EvolutionItemRequirement_RawValue(EvolvePokemonMessage *message, int32_t value);

#pragma mark - FortDeployPokemonMessage

typedef GPB_ENUM(FortDeployPokemonMessage_FieldNumber) {
  FortDeployPokemonMessage_FieldNumber_FortId = 1,
  FortDeployPokemonMessage_FieldNumber_PokemonId = 2,
  FortDeployPokemonMessage_FieldNumber_PlayerLatitude = 3,
  FortDeployPokemonMessage_FieldNumber_PlayerLongitude = 4,
};

@interface FortDeployPokemonMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - FortDetailsMessage

typedef GPB_ENUM(FortDetailsMessage_FieldNumber) {
  FortDetailsMessage_FieldNumber_FortId = 1,
  FortDetailsMessage_FieldNumber_Latitude = 2,
  FortDetailsMessage_FieldNumber_Longitude = 3,
};

@interface FortDetailsMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@end

#pragma mark - FortRecallPokemonMessage

typedef GPB_ENUM(FortRecallPokemonMessage_FieldNumber) {
  FortRecallPokemonMessage_FieldNumber_FortId = 1,
  FortRecallPokemonMessage_FieldNumber_PokemonId = 2,
  FortRecallPokemonMessage_FieldNumber_PlayerLatitude = 3,
  FortRecallPokemonMessage_FieldNumber_PlayerLongitude = 4,
};

@interface FortRecallPokemonMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - FortSearchMessage

typedef GPB_ENUM(FortSearchMessage_FieldNumber) {
  FortSearchMessage_FieldNumber_FortId = 1,
  FortSearchMessage_FieldNumber_PlayerLatitude = 2,
  FortSearchMessage_FieldNumber_PlayerLongitude = 3,
  FortSearchMessage_FieldNumber_FortLatitude = 4,
  FortSearchMessage_FieldNumber_FortLongitude = 5,
};

@interface FortSearchMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *fortId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@property(nonatomic, readwrite) double fortLatitude;

@property(nonatomic, readwrite) double fortLongitude;

@end

#pragma mark - GetAssetDigestMessage

typedef GPB_ENUM(GetAssetDigestMessage_FieldNumber) {
  GetAssetDigestMessage_FieldNumber_Platform = 1,
  GetAssetDigestMessage_FieldNumber_DeviceManufacturer = 2,
  GetAssetDigestMessage_FieldNumber_DeviceModel = 3,
  GetAssetDigestMessage_FieldNumber_Locale = 4,
  GetAssetDigestMessage_FieldNumber_AppVersion = 5,
  GetAssetDigestMessage_FieldNumber_Paginate = 6,
  GetAssetDigestMessage_FieldNumber_PageOffset = 7,
  GetAssetDigestMessage_FieldNumber_PageTimestamp = 8,
};

@interface GetAssetDigestMessage : GPBMessage

@property(nonatomic, readwrite) enum Platform platform;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceManufacturer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceModel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

@property(nonatomic, readwrite) uint32_t appVersion;

@property(nonatomic, readwrite) BOOL paginate;

@property(nonatomic, readwrite) int32_t pageOffset;

@property(nonatomic, readwrite) uint64_t pageTimestamp;

@end

/**
 * Fetches the raw value of a @c GetAssetDigestMessage's @c platform property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetAssetDigestMessage_Platform_RawValue(GetAssetDigestMessage *message);
/**
 * Sets the raw value of an @c GetAssetDigestMessage's @c platform property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetAssetDigestMessage_Platform_RawValue(GetAssetDigestMessage *message, int32_t value);

#pragma mark - GetBuddyWalkedMessage

@interface GetBuddyWalkedMessage : GPBMessage

@end

#pragma mark - GetDownloadUrlsMessage

typedef GPB_ENUM(GetDownloadUrlsMessage_FieldNumber) {
  GetDownloadUrlsMessage_FieldNumber_AssetIdArray = 1,
};

@interface GetDownloadUrlsMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *assetIdArray;
/** The number of items in @c assetIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assetIdArray_Count;

@end

#pragma mark - GetGymDetailsMessage

typedef GPB_ENUM(GetGymDetailsMessage_FieldNumber) {
  GetGymDetailsMessage_FieldNumber_GymId = 1,
  GetGymDetailsMessage_FieldNumber_PlayerLatitude = 2,
  GetGymDetailsMessage_FieldNumber_PlayerLongitude = 3,
  GetGymDetailsMessage_FieldNumber_GymLatitude = 4,
  GetGymDetailsMessage_FieldNumber_GymLongitude = 5,
  GetGymDetailsMessage_FieldNumber_ClientVersion = 6,
};

@interface GetGymDetailsMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *gymId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@property(nonatomic, readwrite) double gymLatitude;

@property(nonatomic, readwrite) double gymLongitude;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientVersion;

@end

#pragma mark - GetHatchedEggsMessage

/**
 * No message needed.
 **/
@interface GetHatchedEggsMessage : GPBMessage

@end

#pragma mark - GetInboxMessage

/**
 * No message needed.
 **/
@interface GetInboxMessage : GPBMessage

@end

#pragma mark - GetIncensePokemonMessage

typedef GPB_ENUM(GetIncensePokemonMessage_FieldNumber) {
  GetIncensePokemonMessage_FieldNumber_PlayerLatitude = 1,
  GetIncensePokemonMessage_FieldNumber_PlayerLongitude = 2,
};

@interface GetIncensePokemonMessage : GPBMessage

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - GetInventoryMessage

typedef GPB_ENUM(GetInventoryMessage_FieldNumber) {
  GetInventoryMessage_FieldNumber_LastTimestampMs = 1,
  GetInventoryMessage_FieldNumber_ItemBeenSeen = 2,
};

@interface GetInventoryMessage : GPBMessage

@property(nonatomic, readwrite) int64_t lastTimestampMs;

/** TODO: Find out what this is. */
@property(nonatomic, readwrite) int32_t itemBeenSeen;

@end

#pragma mark - GetMapObjectsMessage

typedef GPB_ENUM(GetMapObjectsMessage_FieldNumber) {
  GetMapObjectsMessage_FieldNumber_CellIdArray = 1,
  GetMapObjectsMessage_FieldNumber_SinceTimestampMsArray = 2,
  GetMapObjectsMessage_FieldNumber_Latitude = 3,
  GetMapObjectsMessage_FieldNumber_Longitude = 4,
};

@interface GetMapObjectsMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *cellIdArray;
/** The number of items in @c cellIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cellIdArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *sinceTimestampMsArray;
/** The number of items in @c sinceTimestampMsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sinceTimestampMsArray_Count;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@end

#pragma mark - GetPlayerMessage

typedef GPB_ENUM(GetPlayerMessage_FieldNumber) {
  GetPlayerMessage_FieldNumber_PlayerLocale = 1,
};

@interface GetPlayerMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GetPlayerMessage_PlayerLocale *playerLocale;
/** Test to see if @c playerLocale has been set. */
@property(nonatomic, readwrite) BOOL hasPlayerLocale;

@end

#pragma mark - GetPlayerMessage_PlayerLocale

typedef GPB_ENUM(GetPlayerMessage_PlayerLocale_FieldNumber) {
  GetPlayerMessage_PlayerLocale_FieldNumber_Country = 1,
  GetPlayerMessage_PlayerLocale_FieldNumber_Language = 2,
  GetPlayerMessage_PlayerLocale_FieldNumber_Timezone = 3,
};

@interface GetPlayerMessage_PlayerLocale : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *country;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;

@property(nonatomic, readwrite, copy, null_resettable) NSString *timezone;

@end

#pragma mark - GetPlayerProfileMessage

typedef GPB_ENUM(GetPlayerProfileMessage_FieldNumber) {
  GetPlayerProfileMessage_FieldNumber_PlayerName = 1,
};

@interface GetPlayerProfileMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *playerName;

@end

#pragma mark - IncenseEncounterMessage

typedef GPB_ENUM(IncenseEncounterMessage_FieldNumber) {
  IncenseEncounterMessage_FieldNumber_EncounterId = 1,
  IncenseEncounterMessage_FieldNumber_EncounterLocation = 2,
};

@interface IncenseEncounterMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *encounterLocation;

@end

#pragma mark - LevelUpRewardsMessage

typedef GPB_ENUM(LevelUpRewardsMessage_FieldNumber) {
  LevelUpRewardsMessage_FieldNumber_Level = 1,
};

@interface LevelUpRewardsMessage : GPBMessage

@property(nonatomic, readwrite) int32_t level;

@end

#pragma mark - ListAvatarCustomizationsMessage

typedef GPB_ENUM(ListAvatarCustomizationsMessage_FieldNumber) {
  ListAvatarCustomizationsMessage_FieldNumber_AvatarType = 1,
  ListAvatarCustomizationsMessage_FieldNumber_SlotArray = 2,
  ListAvatarCustomizationsMessage_FieldNumber_FiltersArray = 3,
  ListAvatarCustomizationsMessage_FieldNumber_Start = 4,
  ListAvatarCustomizationsMessage_FieldNumber_Limit = 5,
};

@interface ListAvatarCustomizationsMessage : GPBMessage

@property(nonatomic, readwrite) enum PlayerAvatarType avatarType;

// |slotArray| contains |Slot|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *slotArray;
/** The number of items in @c slotArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger slotArray_Count;

// |filtersArray| contains |Filter|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *filtersArray;
/** The number of items in @c filtersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filtersArray_Count;

@property(nonatomic, readwrite) int32_t start;

@property(nonatomic, readwrite) int32_t limit;

@end

/**
 * Fetches the raw value of a @c ListAvatarCustomizationsMessage's @c avatarType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ListAvatarCustomizationsMessage_AvatarType_RawValue(ListAvatarCustomizationsMessage *message);
/**
 * Sets the raw value of an @c ListAvatarCustomizationsMessage's @c avatarType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetListAvatarCustomizationsMessage_AvatarType_RawValue(ListAvatarCustomizationsMessage *message, int32_t value);

#pragma mark - MarkTutorialCompleteMessage

typedef GPB_ENUM(MarkTutorialCompleteMessage_FieldNumber) {
  MarkTutorialCompleteMessage_FieldNumber_TutorialsCompletedArray = 1,
  MarkTutorialCompleteMessage_FieldNumber_SendMarketingEmails = 2,
  MarkTutorialCompleteMessage_FieldNumber_SendPushNotifications = 3,
};

@interface MarkTutorialCompleteMessage : GPBMessage

// |tutorialsCompletedArray| contains |TutorialState|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *tutorialsCompletedArray;
/** The number of items in @c tutorialsCompletedArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tutorialsCompletedArray_Count;

@property(nonatomic, readwrite) BOOL sendMarketingEmails;

@property(nonatomic, readwrite) BOOL sendPushNotifications;

@end

#pragma mark - NicknamePokemonMessage

typedef GPB_ENUM(NicknamePokemonMessage_FieldNumber) {
  NicknamePokemonMessage_FieldNumber_PokemonId = 1,
  NicknamePokemonMessage_FieldNumber_Nickname = 2,
};

@interface NicknamePokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@end

#pragma mark - RecycleInventoryItemMessage

typedef GPB_ENUM(RecycleInventoryItemMessage_FieldNumber) {
  RecycleInventoryItemMessage_FieldNumber_ItemId = 1,
  RecycleInventoryItemMessage_FieldNumber_Count = 2,
};

@interface RecycleInventoryItemMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite) int32_t count;

@end

/**
 * Fetches the raw value of a @c RecycleInventoryItemMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RecycleInventoryItemMessage_ItemId_RawValue(RecycleInventoryItemMessage *message);
/**
 * Sets the raw value of an @c RecycleInventoryItemMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRecycleInventoryItemMessage_ItemId_RawValue(RecycleInventoryItemMessage *message, int32_t value);

#pragma mark - RegisterBackgroundDeviceMessage

typedef GPB_ENUM(RegisterBackgroundDeviceMessage_FieldNumber) {
  RegisterBackgroundDeviceMessage_FieldNumber_DeviceType = 1,
  RegisterBackgroundDeviceMessage_FieldNumber_DeviceId = 2,
};

@interface RegisterBackgroundDeviceMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

@end

#pragma mark - ReleasePokemonMessage

typedef GPB_ENUM(ReleasePokemonMessage_FieldNumber) {
  ReleasePokemonMessage_FieldNumber_PokemonId = 1,
  ReleasePokemonMessage_FieldNumber_PokemonIdsArray = 2,
};

@interface ReleasePokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *pokemonIdsArray;
/** The number of items in @c pokemonIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pokemonIdsArray_Count;

@end

#pragma mark - SetAvatarItemAsViewedMessage

typedef GPB_ENUM(SetAvatarItemAsViewedMessage_FieldNumber) {
  SetAvatarItemAsViewedMessage_FieldNumber_AvatarTemplateIdArray = 1,
};

@interface SetAvatarItemAsViewedMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *avatarTemplateIdArray;
/** The number of items in @c avatarTemplateIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger avatarTemplateIdArray_Count;

@end

#pragma mark - SetAvatarMessage

typedef GPB_ENUM(SetAvatarMessage_FieldNumber) {
  SetAvatarMessage_FieldNumber_PlayerAvatar = 2,
};

@interface SetAvatarMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PlayerAvatar *playerAvatar;
/** Test to see if @c playerAvatar has been set. */
@property(nonatomic, readwrite) BOOL hasPlayerAvatar;

@end

#pragma mark - SetBuddyPokemonMessage

typedef GPB_ENUM(SetBuddyPokemonMessage_FieldNumber) {
  SetBuddyPokemonMessage_FieldNumber_PokemonId = 1,
};

@interface SetBuddyPokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@end

#pragma mark - SetContactSettingsMessage

typedef GPB_ENUM(SetContactSettingsMessage_FieldNumber) {
  SetContactSettingsMessage_FieldNumber_ContactSettings = 1,
};

@interface SetContactSettingsMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) ContactSettings *contactSettings;
/** Test to see if @c contactSettings has been set. */
@property(nonatomic, readwrite) BOOL hasContactSettings;

@end

#pragma mark - SetFavoritePokemonMessage

typedef GPB_ENUM(SetFavoritePokemonMessage_FieldNumber) {
  SetFavoritePokemonMessage_FieldNumber_PokemonId = 1,
  SetFavoritePokemonMessage_FieldNumber_IsFavorite = 2,
};

@interface SetFavoritePokemonMessage : GPBMessage

/** Do not change https://github.com/AeonLucid/POGOProtos/pull/126 */
@property(nonatomic, readwrite) int64_t pokemonId;

@property(nonatomic, readwrite) BOOL isFavorite;

@end

#pragma mark - SetPlayerTeamMessage

typedef GPB_ENUM(SetPlayerTeamMessage_FieldNumber) {
  SetPlayerTeamMessage_FieldNumber_Team = 1,
};

@interface SetPlayerTeamMessage : GPBMessage

@property(nonatomic, readwrite) enum TeamColor team;

@end

/**
 * Fetches the raw value of a @c SetPlayerTeamMessage's @c team property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SetPlayerTeamMessage_Team_RawValue(SetPlayerTeamMessage *message);
/**
 * Sets the raw value of an @c SetPlayerTeamMessage's @c team property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSetPlayerTeamMessage_Team_RawValue(SetPlayerTeamMessage *message, int32_t value);

#pragma mark - SfidaActionLogMessage

/**
 * No message needed.
 **/
@interface SfidaActionLogMessage : GPBMessage

@end

#pragma mark - StartGymBattleMessage

typedef GPB_ENUM(StartGymBattleMessage_FieldNumber) {
  StartGymBattleMessage_FieldNumber_GymId = 1,
  StartGymBattleMessage_FieldNumber_AttackingPokemonIdsArray = 2,
  StartGymBattleMessage_FieldNumber_DefendingPokemonId = 3,
  StartGymBattleMessage_FieldNumber_PlayerLatitude = 4,
  StartGymBattleMessage_FieldNumber_PlayerLongitude = 5,
};

@interface StartGymBattleMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *gymId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *attackingPokemonIdsArray;
/** The number of items in @c attackingPokemonIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger attackingPokemonIdsArray_Count;

/** needs to be fixed64, tested by Grover */
@property(nonatomic, readwrite) uint64_t defendingPokemonId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

#pragma mark - UpdateNotificationMessage

typedef GPB_ENUM(UpdateNotificationMessage_FieldNumber) {
  UpdateNotificationMessage_FieldNumber_NotificationIdsArray = 1,
  UpdateNotificationMessage_FieldNumber_CreateTimestampMsArray = 2,
  UpdateNotificationMessage_FieldNumber_State = 3,
};

@interface UpdateNotificationMessage : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *notificationIdsArray;
/** The number of items in @c notificationIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger notificationIdsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *createTimestampMsArray;
/** The number of items in @c createTimestampMsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger createTimestampMsArray_Count;

@property(nonatomic, readwrite) enum NotificationState state;

@end

/**
 * Fetches the raw value of a @c UpdateNotificationMessage's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UpdateNotificationMessage_State_RawValue(UpdateNotificationMessage *message);
/**
 * Sets the raw value of an @c UpdateNotificationMessage's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUpdateNotificationMessage_State_RawValue(UpdateNotificationMessage *message, int32_t value);

#pragma mark - UpgradePokemonMessage

typedef GPB_ENUM(UpgradePokemonMessage_FieldNumber) {
  UpgradePokemonMessage_FieldNumber_PokemonId = 1,
};

@interface UpgradePokemonMessage : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@end

#pragma mark - UseIncenseMessage

typedef GPB_ENUM(UseIncenseMessage_FieldNumber) {
  UseIncenseMessage_FieldNumber_IncenseType = 1,
};

@interface UseIncenseMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId incenseType;

@end

/**
 * Fetches the raw value of a @c UseIncenseMessage's @c incenseType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseIncenseMessage_IncenseType_RawValue(UseIncenseMessage *message);
/**
 * Sets the raw value of an @c UseIncenseMessage's @c incenseType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseIncenseMessage_IncenseType_RawValue(UseIncenseMessage *message, int32_t value);

#pragma mark - UseItemCaptureMessage

typedef GPB_ENUM(UseItemCaptureMessage_FieldNumber) {
  UseItemCaptureMessage_FieldNumber_ItemId = 1,
  UseItemCaptureMessage_FieldNumber_EncounterId = 2,
  UseItemCaptureMessage_FieldNumber_SpawnPointId = 3,
};

@interface UseItemCaptureMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointId;

@end

/**
 * Fetches the raw value of a @c UseItemCaptureMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemCaptureMessage_ItemId_RawValue(UseItemCaptureMessage *message);
/**
 * Sets the raw value of an @c UseItemCaptureMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemCaptureMessage_ItemId_RawValue(UseItemCaptureMessage *message, int32_t value);

#pragma mark - UseItemEggIncubatorMessage

typedef GPB_ENUM(UseItemEggIncubatorMessage_FieldNumber) {
  UseItemEggIncubatorMessage_FieldNumber_ItemId = 1,
  UseItemEggIncubatorMessage_FieldNumber_PokemonId = 2,
};

@interface UseItemEggIncubatorMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *itemId;

@property(nonatomic, readwrite) uint64_t pokemonId;

@end

#pragma mark - UseItemEncounterMessage

typedef GPB_ENUM(UseItemEncounterMessage_FieldNumber) {
  UseItemEncounterMessage_FieldNumber_Item = 1,
  UseItemEncounterMessage_FieldNumber_EncounterId = 2,
  UseItemEncounterMessage_FieldNumber_SpawnPointGuid = 3,
};

@interface UseItemEncounterMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId item;

@property(nonatomic, readwrite) uint64_t encounterId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *spawnPointGuid;

@end

/**
 * Fetches the raw value of a @c UseItemEncounterMessage's @c item property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemEncounterMessage_Item_RawValue(UseItemEncounterMessage *message);
/**
 * Sets the raw value of an @c UseItemEncounterMessage's @c item property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemEncounterMessage_Item_RawValue(UseItemEncounterMessage *message, int32_t value);

#pragma mark - UseItemGymMessage

typedef GPB_ENUM(UseItemGymMessage_FieldNumber) {
  UseItemGymMessage_FieldNumber_ItemId = 1,
  UseItemGymMessage_FieldNumber_GymId = 2,
  UseItemGymMessage_FieldNumber_PlayerLatitude = 3,
  UseItemGymMessage_FieldNumber_PlayerLongitude = 4,
};

@interface UseItemGymMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gymId;

@property(nonatomic, readwrite) double playerLatitude;

@property(nonatomic, readwrite) double playerLongitude;

@end

/**
 * Fetches the raw value of a @c UseItemGymMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemGymMessage_ItemId_RawValue(UseItemGymMessage *message);
/**
 * Sets the raw value of an @c UseItemGymMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemGymMessage_ItemId_RawValue(UseItemGymMessage *message, int32_t value);

#pragma mark - UseItemPotionMessage

typedef GPB_ENUM(UseItemPotionMessage_FieldNumber) {
  UseItemPotionMessage_FieldNumber_ItemId = 1,
  UseItemPotionMessage_FieldNumber_PokemonId = 2,
};

@interface UseItemPotionMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite) uint64_t pokemonId;

@end

/**
 * Fetches the raw value of a @c UseItemPotionMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemPotionMessage_ItemId_RawValue(UseItemPotionMessage *message);
/**
 * Sets the raw value of an @c UseItemPotionMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemPotionMessage_ItemId_RawValue(UseItemPotionMessage *message, int32_t value);

#pragma mark - UseItemReviveMessage

typedef GPB_ENUM(UseItemReviveMessage_FieldNumber) {
  UseItemReviveMessage_FieldNumber_ItemId = 1,
  UseItemReviveMessage_FieldNumber_PokemonId = 2,
};

@interface UseItemReviveMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@property(nonatomic, readwrite) uint64_t pokemonId;

@end

/**
 * Fetches the raw value of a @c UseItemReviveMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemReviveMessage_ItemId_RawValue(UseItemReviveMessage *message);
/**
 * Sets the raw value of an @c UseItemReviveMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemReviveMessage_ItemId_RawValue(UseItemReviveMessage *message, int32_t value);

#pragma mark - UseItemXpBoostMessage

typedef GPB_ENUM(UseItemXpBoostMessage_FieldNumber) {
  UseItemXpBoostMessage_FieldNumber_ItemId = 1,
};

@interface UseItemXpBoostMessage : GPBMessage

@property(nonatomic, readwrite) enum ItemId itemId;

@end

/**
 * Fetches the raw value of a @c UseItemXpBoostMessage's @c itemId property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UseItemXpBoostMessage_ItemId_RawValue(UseItemXpBoostMessage *message);
/**
 * Sets the raw value of an @c UseItemXpBoostMessage's @c itemId property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUseItemXpBoostMessage_ItemId_RawValue(UseItemXpBoostMessage *message, int32_t value);

#pragma mark - VerifyChallengeMessage

typedef GPB_ENUM(VerifyChallengeMessage_FieldNumber) {
  VerifyChallengeMessage_FieldNumber_Token = 1,
};

@interface VerifyChallengeMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
