// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos.Data.Redeem.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "PogoprotosInventoryItem.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(ItemId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PogoprotosDataRedeemRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PogoprotosDataRedeemRoot : GPBRootObject
@end

#pragma mark - PokeCandy

typedef GPB_ENUM(PokeCandy_FieldNumber) {
  PokeCandy_FieldNumber_PokemonId = 1,
  PokeCandy_FieldNumber_CandyCount = 2,
};

@interface PokeCandy : GPBMessage

@property(nonatomic, readwrite) uint64_t pokemonId;

@property(nonatomic, readwrite) int32_t candyCount;

@end

#pragma mark - RedeemedAvatarItem

typedef GPB_ENUM(RedeemedAvatarItem_FieldNumber) {
  RedeemedAvatarItem_FieldNumber_AvatarTemplateId = 1,
  RedeemedAvatarItem_FieldNumber_ItemCount = 2,
};

@interface RedeemedAvatarItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatarTemplateId;

@property(nonatomic, readwrite) int32_t itemCount;

@end

#pragma mark - RedeemedItem

typedef GPB_ENUM(RedeemedItem_FieldNumber) {
  RedeemedItem_FieldNumber_Item = 1,
  RedeemedItem_FieldNumber_ItemCount = 2,
};

@interface RedeemedItem : GPBMessage

@property(nonatomic, readwrite) enum ItemId item;

@property(nonatomic, readwrite) int32_t itemCount;

@end

/**
 * Fetches the raw value of a @c RedeemedItem's @c item property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RedeemedItem_Item_RawValue(RedeemedItem *message);
/**
 * Sets the raw value of an @c RedeemedItem's @c item property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRedeemedItem_Item_RawValue(RedeemedItem *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
